In [19]:
#Generating Traits Data for BAYC

In [20]:
import pandas as pd
df = pd.read_csv('apes_dataset_only_scores_w.csv')
print(df)

      Unnamed: 0     Score  tokenId
0              0  1.134250        1
1              1  0.937322        2
2              2  0.835999        3
3              3  0.824098        4
4              4  0.878616        5
...          ...       ...      ...
9995        9995  1.165977     9996
9996        9996  0.717161     9997
9997        9997  0.830929     9998
9998        9998  1.438040     9999
9999        9999  1.368174    10000

[10000 rows x 3 columns]


In [21]:
import numpy

In [22]:
myList = df['Score'].tolist()

In [ ]:
myList

In [23]:
temp = numpy.argsort(myList)
temp

array([2056, 4967, 4042, ..., 1905, 2509, 7494])

In [24]:
numpy.where(temp == 0)

(array([7194]),)

In [25]:
#1652, 7622, 3933


# '1:{1.1342495346394266,2806}',
# '2:{0.937321652058925,4270}',
# '3:{0.8359986902678298,7147}'

In [26]:
myList[7215]

1.2122652710492756

In [27]:
print(myList[1652])
print(myList[7622])
print(myList[3933])
print()
print()
print()
print(myList[324])
print(myList[2979])
print(myList[2564])

1.215139447006208
1.2719471967013465
0.7938659371220409



0.965836479081768
1.3064984769983827
0.8056970337000627


In [35]:
np_array = numpy.array([numpy.where(temp == index)[0] + 1 for index in range(10000)])

In [39]:
np_array

array([[7195],
       [5731],
       [2854],
       ...,
       [2670],
       [9382],
       [9018]])

In [40]:
np_array_new = 10001 - np_array

In [38]:
np_array_new

array([[2806],
       [4270],
       [7147],
       ...,
       [7331],
       [ 619],
       [ 983]])

In [109]:
BAYC = dict()

In [110]:
for index, row in df.iterrows():  
    BAYC[str(int(row['tokenId']))] = {"Score":str(round(row['Score'],4)),"Rank":str(np_array_new[index][0])}


In [111]:
BAYC

{'1': {'Score': '1.1342', 'Rank': '2806'},
 '2': {'Score': '0.9373', 'Rank': '4270'},
 '3': {'Score': '0.836', 'Rank': '7147'},
 '4': {'Score': '0.8241', 'Rank': '7584'},
 '5': {'Score': '0.8786', 'Rank': '5789'},
 '6': {'Score': '0.9009', 'Rank': '5192'},
 '7': {'Score': '0.8864', 'Rank': '5575'},
 '8': {'Score': '1.475', 'Rank': '493'},
 '9': {'Score': '1.1409', 'Rank': '2760'},
 '10': {'Score': '1.0158', 'Rank': '3312'},
 '11': {'Score': '0.7842', 'Rank': '8775'},
 '12': {'Score': '0.8022', 'Rank': '8315'},
 '13': {'Score': '0.8127', 'Rank': '7975'},
 '14': {'Score': '1.6122', 'Rank': '163'},
 '15': {'Score': '0.9544', 'Rank': '3937'},
 '16': {'Score': '1.07', 'Rank': '3068'},
 '17': {'Score': '1.3816', 'Rank': '920'},
 '18': {'Score': '1.0854', 'Rank': '3003'},
 '19': {'Score': '0.8822', 'Rank': '5677'},
 '20': {'Score': '0.9165', 'Rank': '4769'},
 '21': {'Score': '0.7281', 'Rank': '9657'},
 '22': {'Score': '1.453', 'Rank': '551'},
 '23': {'Score': '0.9605', 'Rank': '3852'},
 '24':

In [112]:
import json
BAYC_data = json.dumps(BAYC)

In [113]:
BAYC_data

'{"1": {"Score": "1.1342", "Rank": "2806"}, "2": {"Score": "0.9373", "Rank": "4270"}, "3": {"Score": "0.836", "Rank": "7147"}, "4": {"Score": "0.8241", "Rank": "7584"}, "5": {"Score": "0.8786", "Rank": "5789"}, "6": {"Score": "0.9009", "Rank": "5192"}, "7": {"Score": "0.8864", "Rank": "5575"}, "8": {"Score": "1.475", "Rank": "493"}, "9": {"Score": "1.1409", "Rank": "2760"}, "10": {"Score": "1.0158", "Rank": "3312"}, "11": {"Score": "0.7842", "Rank": "8775"}, "12": {"Score": "0.8022", "Rank": "8315"}, "13": {"Score": "0.8127", "Rank": "7975"}, "14": {"Score": "1.6122", "Rank": "163"}, "15": {"Score": "0.9544", "Rank": "3937"}, "16": {"Score": "1.07", "Rank": "3068"}, "17": {"Score": "1.3816", "Rank": "920"}, "18": {"Score": "1.0854", "Rank": "3003"}, "19": {"Score": "0.8822", "Rank": "5677"}, "20": {"Score": "0.9165", "Rank": "4769"}, "21": {"Score": "0.7281", "Rank": "9657"}, "22": {"Score": "1.453", "Rank": "551"}, "23": {"Score": "0.9605", "Rank": "3852"}, "24": {"Score": "0.8818", "

In [191]:
import pandas as pd
df_MAYC = pd.read_csv('Mutant_apes_dataset_only_scores_w.csv')

In [192]:
df_MAYC.drop('Unnamed: 0', axis=1, inplace=True) 
df_MAYC.head()


Score  tokenId
0  1.352463        1
1  1.363444        2
2  0.978770        3
3  1.113749        4
4  1.303695        5

In [193]:
df_MAYC

Score  tokenId
0      1.352463        1
1      1.363444        2
2      0.978770        3
3      1.113749        4
4      1.303695        5
...         ...      ...
9996   1.386786     9997
9997   0.195669     9998
9998   1.824218     9999
9999   0.178357    10000
10000  0.197709    10002

[10001 rows x 2 columns]

In [194]:
myListMAYC = df_MAYC['Score'].tolist()

In [195]:
temp_MAYC = numpy.argsort(myListMAYC)
temp_MAYC

array([1652, 7622, 3933, ...,  324, 2979, 2564])

In [196]:
np_array = numpy.array([numpy.where(temp_MAYC == index)[0] + 1 for index in range(10001)])

In [197]:
np_array

array([[7216],
       [7276],
       [4988],
       ...,
       [9121],
       [ 425],
       [ 972]])

In [198]:
np_array_new_MAYC = 10002 - np_array

In [199]:
np_array_new_MAYC

array([[2786],
       [2726],
       [5014],
       ...,
       [ 881],
       [9577],
       [9030]])

In [200]:
MAYC = dict()

In [201]:
for index, row in df_MAYC.iterrows():  
    MAYC[str(int(row['tokenId']))] = {"Score":str(round(row['Score'],4)),"Rank":str(np_array_new_MAYC[index][0])}


In [202]:
MAYC

{'1': {'Score': '1.3525', 'Rank': '2786'},
 '2': {'Score': '1.3634', 'Rank': '2726'},
 '3': {'Score': '0.9788', 'Rank': '5014'},
 '4': {'Score': '1.1137', 'Rank': '3850'},
 '5': {'Score': '1.3037', 'Rank': '2986'},
 '6': {'Score': '0.8224', 'Rank': '6620'},
 '7': {'Score': '0.6355', 'Rank': '7401'},
 '8': {'Score': '1.0875', 'Rank': '4175'},
 '9': {'Score': '0.9346', 'Rank': '5446'},
 '10': {'Score': '0.2014', 'Rank': '8789'},
 '11': {'Score': '1.4959', 'Rank': '2071'},
 '12': {'Score': '0.2451', 'Rank': '8012'},
 '13': {'Score': '1.3534', 'Rank': '2779'},
 '14': {'Score': '1.1443', 'Rank': '3672'},
 '15': {'Score': '1.5539', 'Rank': '1771'},
 '16': {'Score': '1.1443', 'Rank': '3675'},
 '17': {'Score': '1.086', 'Rank': '4203'},
 '18': {'Score': '1.4109', 'Rank': '2476'},
 '19': {'Score': '0.9547', 'Rank': '5149'},
 '20': {'Score': '0.7403', 'Rank': '7184'},
 '21': {'Score': '0.9656', 'Rank': '5078'},
 '22': {'Score': '2.169', 'Rank': '206'},
 '23': {'Score': '1.0377', 'Rank': '4625'},


In [203]:
MAYC_data = json.dumps(MAYC)
MAYC_data

'{"1": {"Score": "1.3525", "Rank": "2786"}, "2": {"Score": "1.3634", "Rank": "2726"}, "3": {"Score": "0.9788", "Rank": "5014"}, "4": {"Score": "1.1137", "Rank": "3850"}, "5": {"Score": "1.3037", "Rank": "2986"}, "6": {"Score": "0.8224", "Rank": "6620"}, "7": {"Score": "0.6355", "Rank": "7401"}, "8": {"Score": "1.0875", "Rank": "4175"}, "9": {"Score": "0.9346", "Rank": "5446"}, "10": {"Score": "0.2014", "Rank": "8789"}, "11": {"Score": "1.4959", "Rank": "2071"}, "12": {"Score": "0.2451", "Rank": "8012"}, "13": {"Score": "1.3534", "Rank": "2779"}, "14": {"Score": "1.1443", "Rank": "3672"}, "15": {"Score": "1.5539", "Rank": "1771"}, "16": {"Score": "1.1443", "Rank": "3675"}, "17": {"Score": "1.086", "Rank": "4203"}, "18": {"Score": "1.4109", "Rank": "2476"}, "19": {"Score": "0.9547", "Rank": "5149"}, "20": {"Score": "0.7403", "Rank": "7184"}, "21": {"Score": "0.9656", "Rank": "5078"}, "22": {"Score": "2.169", "Rank": "206"}, "23": {"Score": "1.0377", "Rank": "4625"}, "24": {"Score": "0.19